= Minikube Template

== Instalación

Para iniciar el clúster de Minikube, ejecute el siguiente comando en la terminal:

./minikube/minikube-install.sh

Esto ejecutará el script de instalación que configura Minikube con el perfil adecuado.

== Namespaces utilizados

|===
| Namespace | Descripción
| `applications` | Namespace para aplicaciones desplegadas en el clúster.
| `cert-manager` | Namespace para recursos relacionados con la gestión de certificados.
| `cicd` | Namespace para recursos relacionados con CI/CD.
|===

== Módulos

=== Cert-Manager

Cert-Manager es una herramienta que automatiza la gestión de certificados TLS en Kubernetes. En este proyecto, se utiliza para gestionar los certificados necesarios para asegurar las comunicaciones dentro del clúster.

Para ello utilizaremos un cerfificado autofirmado generado a partir de openssl, el cual se encuentra en el directorio `certs` y se llama `ca.crt`. Este certificado se utilizará para crear un Issuer en Cert-Manager, que luego se usará para emitir certificados TLS para nuestras aplicaciones.

=== ArgoCD

Instalación básica de ArgoCD utilizando Helm. Para acceder a la interfaz de usuario de ArgoCD, se puede utilizar el siguiente comando para hacer un port-forwarding:

[source,bash]
----
kubectl port-forward service/argocd-server -n cicd 8080:443
----

WARNING: TODO: Fix Ingress TLS

Podemos instalar la aplicación de ejemplo https://github.com/labcabrera/sample-users-api utilizando el manifiesto `sample-users-api-argocd-project.yaml` ubicado en `modules/argocd/sample-projects/`.

Esto utilizará kustomize para desplegar los recursos definidos en el repositorio de ejemplo, lo que nos permitirá ver cómo ArgoCD gestiona las aplicaciones desplegadas en el clúster.

Para verificar que nuestra aplicación se ha desplegado correctamente ejecutaremos:

[source,bash]
----
curl -v --insecure https://sample-users-api.local/actuator/health
----

TIP: Deberemos haber agregado una entrada en nuestro archivo `/etc/hosts` para resolver `sample-users-api.local` a la IP de Minikube que podremos obtener ejecutando `minikube ip -p minikube-template`.