= Minikube Template

== Instalación

Para iniciar el clúster de Minikube, ejecute el siguiente comando en la terminal:

./minikube/minikube-install.sh

Esto ejecutará el script de instalación que configura Minikube con el perfil adecuado.

== Namespaces utilizados

|===
| Namespace | Descripción
| `applications` | Namespace para aplicaciones desplegadas en el clúster.
| `cert-manager` | Namespace para recursos relacionados con la gestión de certificados.
| `cicd` | Namespace para recursos relacionados con CI/CD.
|===

== Módulos

=== Cert-Manager

Cert-Manager es una herramienta que automatiza la gestión de certificados TLS en Kubernetes. En este proyecto, se utiliza para gestionar los certificados necesarios para asegurar las comunicaciones dentro del clúster.

Para ello utilizaremos un cerfificado autofirmado generado a partir de openssl, el cual se encuentra en el directorio `certs` y se llama `ca.crt`. Este certificado se utilizará para crear un Issuer en Cert-Manager, que luego se usará para emitir certificados TLS para nuestras aplicaciones.

=== ArgoCD

Instalación básica de ArgoCD utilizando Helm. Para acceder a la interfaz de usuario de ArgoCD, se puede utilizar el siguiente comando para hacer un port-forwarding:

[source,bash]
----
kubectl port-forward service/argocd-server -n cicd 8080:443
----

WARNING: TODO: Fix Ingress TLS

Podemos instalar la aplicación de ejemplo https://github.com/labcabrera/sample-users-api utilizando el manifiesto `sample-users-api-argocd-project.yaml` ubicado en `modules/argocd/sample-projects/`.

Esto utilizará kustomize para desplegar los recursos definidos en el repositorio de ejemplo, lo que nos permitirá ver cómo ArgoCD gestiona las aplicaciones desplegadas en el clúster.

Para verificar que nuestra aplicación se ha desplegado correctamente ejecutaremos:

[source,bash]
----
curl -v --insecure https://sample-users-api.local/actuator/health
----

TIP: Deberemos haber agregado una entrada en nuestro archivo `/etc/hosts` para resolver `sample-users-api.local` a la IP de Minikube que podremos obtener ejecutando `minikube ip -p minikube-template`.

=== Kong

En primer lugar instalaremos los CRDs:

[source,bash]
----
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
----

Después realizaremos la instalación de Kong por defecto utilizando Helm:

[source,bash]
----
helm install kong kong/ingress -n kong
----

En nuestro caso como no tenemos un LoadBalancer externo haremos:

[source,bash]
----
cat > values.yaml <<'YAML'
gateway:
  proxy:
    type: NodePort
YAML

helm upgrade --install kong kong/ingress -n kong -f values.yaml
----

Después crearemos el gateway haciendo:

----
kubectl apply -f kong-gateway.yaml
----

Y verificaremos que ha sido creado correctamente:

----
kubectl get gateways -A
NAMESPACE   NAME   CLASS   ADDRESS   PROGRAMMED   AGE
kong        kong   kong              True         3m20s
----

Una vez creado el gateway crearemos una ruta de ejemplo:

----
kubectl apply -f sample-user-api-route.yaml
----

TIP: En esta ruta hemos aplicado la regla de reescritura para que el path de la ruta sea `/` en lugar de `/users`, lo que nos permitirá acceder a la aplicación sin necesidad de incluir el path completo en la URL.

Para comprobar que funciona obtendremos la IP del gateway:

----
minikube service -n kong kong-gateway-proxy --url -p minikube-template
http://192.168.58.2:31698
http://192.168.58.2:31893
----

Y finalmente haremos una petición a la ruta de ejemplo:

----
curl http://192.168.58.2:31698/users/actuator/health

http://192.168.58.2:31893/users/actuator/health

curl --insecure https://192.168.58.2:31893/users/actuator/health
----

