# Usa la imagen de Kong Gateway (Free/Enterprise), que incluye Kong Manager
image:
  repository: kong/kong-gateway

# DB-less (sin PostgreSQL)
env:
  database: "off"

  # Admin API y Kong Manager
  admin_listen: "0.0.0.0:8001"
  admin_gui_listen: "0.0.0.0:8002"

  # URLs (para port-forward local)
  admin_gui_url: "http://localhost:8002"
  admin_gui_api_url: "http://localhost:8001"

  # Sesión (cookie) del Manager (ejemplo mínimo)
  admin_gui_session_conf: '{"secret":"cambia-esto-por-un-secreto-largo","storage":"kong","cookie_secure":false}'

# Habilita Admin API
admin:
  enabled: true
  http:
    enabled: true

# Habilita Kong Manager
manager:
  enabled: true
  http:
    enabled: true