apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: konga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga:latest
        ports:
        - containerPort: 1337
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "1337"
        - name: DB_ADAPTER
          value: "mongo"
        - name: DB_HOST
          # value: "mongodb.mongodb.svc.cluster.local"
          value: "mongodb.mongodb"
        - name: DB_PORT
          value: "27017"
        - name: DB_USER
          value: "mongodb"
        - name: DB_DATABASE
          value: "konga"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: konga-mongo
              key: DB_PASSWORD