apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-user-api
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  source:
    path: k8s
    repoURL: https://github.com/labcabrera/sample-user-api
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
