configs:
  secret:
    #changeit
    argocdServerAdminPassword: '$2y$10$vAKJfNlItZH/h500v0DObOd5IFBAUJifgSLTiVpKzqJ2AKGhqozVy'
server:
  #TODO configure TLS
  insecure: true
  service:
    type: ClusterIP
  # ingress:
  #   enabled: true
  #   ingressClassName: nginx
  #   hostname: argocd.local
  #   path: /
  #   pathType: Prefix
    # tls: false
